import { ColorPalettel } from ".."

const LightScheme: ColorScheme = {
    primary: ColorPalettel.Red,
    onPrimary: ColorPalettel.Red,
    primaryContainer: ColorPalettel.Red,
    onPrimaryContainer: ColorPalettel.Red,
    secondary: ColorPalettel.Red,
    onSecondary: ColorPalettel.Red,
    secondaryContainer: ColorPalettel.Red,
    onSecondaryContainer: ColorPalettel.Red,
    tertiary: ColorPalettel.Red,
    onTertiary: ColorPalettel.Red,
    tertiaryContainer: ColorPalettel.Red,
    onTertiaryContainer: ColorPalettel.Red,
    error: ColorPalettel.Red,
    onError: ColorPalettel.Red,
    errorContainer: ColorPalettel.Red,
    onErrorContainer: ColorPalettel.Red,
    background: ColorPalettel.Red,
    onBackground: ColorPalettel.Red,
    surface: ColorPalettel.Red,
    onSurface: ColorPalettel.Red,
    surfaceVariant: ColorPalettel.Red,
    onSurfaceVariant: ColorPalettel.Red,
    outline: ColorPalettel.Red,
    outlineVariant: ColorPalettel.Red,
    shadow: ColorPalettel.Red,
}

const DarkScheme: ColorScheme = {
    primary: ColorPalettel.Red,
    onPrimary: ColorPalettel.Red,
    primaryContainer: ColorPalettel.Red,
    onPrimaryContainer: ColorPalettel.Red,
    secondary: ColorPalettel.Red,
    onSecondary: ColorPalettel.Red,
    secondaryContainer: ColorPalettel.Red,
    onSecondaryContainer: ColorPalettel.Red,
    tertiary: ColorPalettel.Red,
    onTertiary: ColorPalettel.Red,
    tertiaryContainer: ColorPalettel.Red,
    onTertiaryContainer: ColorPalettel.Red,
    error: ColorPalettel.Red,
    onError: ColorPalettel.Red,
    errorContainer: ColorPalettel.Red,
    onErrorContainer: ColorPalettel.Red,
    background: ColorPalettel.Red,
    onBackground: ColorPalettel.Red,
    surface: ColorPalettel.Red,
    onSurface: ColorPalettel.Red,
    surfaceVariant: ColorPalettel.Red,
    onSurfaceVariant: ColorPalettel.Red,
    outline: ColorPalettel.Red,
    outlineVariant: ColorPalettel.Red,
    shadow: ColorPalettel.Red,
}

export {LightScheme, DarkScheme}