interface ColorScheme {
    primary: string,
    onPrimary: string,
    primaryContainer: string,
    onPrimaryContainer: string,
    secondary: string,
    onSecondary: string,
    secondaryContainer: string,
    onSecondaryContainer: string,
    tertiary: string,
    onTertiary: string,
    tertiaryContainer: string,
    onTertiaryContainer: string,
    error: string,
    onError: string,
    errorContainer: string,
    onErrorContainer: string,
    background: string,
    onBackground: string,
    surface: string,
    onSurface: string,
    surfaceVariant: string,
    onSurfaceVariant: string,
    outline: string,
    outlineVariant: string,
    shadow: string,
    // "elevation": {
    // "level0": "transparent",
    // "level1": "rgb(248, 242, 251)",
    // "level2": "rgb(244, 236, 248)",
    // "level3": "rgb(240, 231, 246)",
    // "level4": "rgb(239, 229, 245)",
    // "level5": "rgb(236, 226, 243)"
    // },       
}